theme: jekyll-theme-minimal
title: "DMap: Domain Name Ecosystem Mapper"
#baseurl: "http://dmap.sidnlabs.nl"
description: "Mapping the DNS ecosystem"

# List of links in the navigation bar
#navbar-links:
 # Source Code: "source/"
  #Research Paper:
  #Demo: "/demo/"

logo: "/img/map2.jpg"

